apiVersion: v1
kind: Service
metadata:
  name: event-generator
  namespace: odins-oddities
  labels:
    app: event-generator
spec:
  selector:
    app: event-generator
  ports:
    - port: 8082
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-generator-deployment
  namespace: odins-oddities
  labels:
    app: event-generator
spec:
  selector:
    matchLabels:
      app: event-generator
  replicas: 1
  template:
    metadata:
      namespace: odins-oddities
      labels:
        app: event-generator
    spec:
      containers:
        - name: event-generator
          image: event-generator:0.0.1-SNAPSHOT
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: event-generator-config
