# https://taskfile.dev

version: "3"

vars:
  TASKFILES_DIR: "./taskfiles"
  NAMESPACE: odins-oddities

includes:
  minikube:
    taskfile: "{{.TASKFILES_DIR}}/minikube.yml"
  postgres:
    taskfile: "{{.TASKFILES_DIR}}/postgres.yml"
    dir: "./k8s/PostgreSQL"
  config-server:
    taskfile: "{{.TASKFILES_DIR}}/config-server.yml"
  product-service:
    taskfile: "{{.TASKFILES_DIR}}/product-service.yml"
