apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: odins-oddities
  labels:
    app: product-service
    monitoring: prometheus
spec:
  selector:
    app: product-service
  ports:
    - name: app
      port: 8081
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-deployment
  namespace: odins-oddities
  labels:
    app: product-service
spec:
  selector:
    matchLabels:
      app: product-service
  replicas: 1
  template:
    metadata:
      namespace: odins-oddities
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: product-service:0.0.1-SNAPSHOT
          imagePullPolicy: Never
          ports:
            - name: app
              containerPort: 8081
          envFrom:
            - configMapRef:
                name: product-service-config
            - secretRef:
                name: product-service-secret
