version: "3"

vars:
  K8S_DIR: "./k8s/Config-Server"
  PROJECT_DIR: "./configserver"

tasks:
  port-forward:
    cmds:
      - kubectl port-forward --address 0.0.0.0 svc/config-server 8888:8888 -n {{.NAMESPACE}}
  create-config:
    requires:
      vars: [POSTGRES_USER, POSTGRES_PASSWORD]
    dir: "{{.K8S_DIR}}"
    cmds:
      - kubectl create secret generic config-server-secret -n {{.NAMESPACE}} --from-literal=POSTGRES_USER='{{.POSTGRES_USER}}' --from-literal=POSTGRES_PASSWORD='{{.POSTGRES_PASSWORD}}'
      - kubectl apply -f ConfigMap.yml
  deploy-app:
    dir: "{{.K8S_DIR}}"
    cmds:
      - kubectl apply -f Deployment.yml
  delete-app:
    dir: "{{.K8S_DIR}}"
    cmds:
      - kubectl delete -f Deployment.yml
  build-image:
    dir: "{{.PROJECT_DIR}}"
    cmds:
      - eval $(minikube -p minikube docker-env) && ./mvnw spring-boot:build-image
  delete-build-deploy:
    cmds:
      - task: delete-app
      - task: build-image
      - task: deploy-app
