version: "3"

vars:
  K8S_DIR: "./k8s/Product-Service"
  PROJECT_DIR: "./product-service"
  PRODUCT_SERVICE_DIR: "./product-service/product-service"

tasks:
  port-forward:
    cmds:
      - kubectl port-forward svc/product-service 8081:8081 -n {{.NAMESPACE}}
  create-config:
    requires:
      vars: [POSTGRES_USER, POSTGRES_PASSWORD]
    dir: "{{.K8S_DIR}}"
    cmds:
      - kubectl create secret generic product-service-secret -n {{.NAMESPACE}} --from-literal=POSTGRES_USER='{{.POSTGRES_USER}}' --from-literal=POSTGRES_PASSWORD='{{.POSTGRES_PASSWORD}}'
      - kubectl apply -f ConfigMap.yml
  deploy-app:
    dir: "{{.K8S_DIR}}"
    cmds:
      - kubectl apply -f Deployment.yml
  delete-app:
    dir: "{{.K8S_DIR}}"
    cmds:
      - kubectl delete -f Deployment.yml
  build-image:
    dir: "{{.PRODUCT_SERVICE_DIR}}/"
    cmds:
      - eval $(minikube -p minikube docker-env) && ./mvnw -DskipTests=true spring-boot:build-image
  delete-build-deploy:
    cmds:
      - task: delete-app
      - task: build-image
      - task: deploy-app
  remove-project-artifact:
    dir: "{{.PROJECT_DIR}}/"
    cmds:
      - ./mvnw build-helper:remove-project-artifact
  generate-openapi-spec:
    dir: "{{.PROJECT_DIR}}"
    dotenv: ["../.env"]
    cmds:
      - ./mvnw clean verify
      - cp ../OpenAPI/product-service.yml ../event-generator/src/main/resources/api/product-service-api.yml
