DROP TABLE IF EXISTS PROPERTIES;

CREATE TABLE PROPERTIES (
    ID SERIAL PRIMARY KEY,
    APPLICATION VARCHAR(255) NOT NULL,
    PROFILE VARCHAR(255) NOT NULL,
    LABEL VARCHAR(255) NOT NULL,
    "KEY" VARCHAR(255) NOT NULL,
    "VALUE" TEXT NOT NULL
);