apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: odins-oddities
  labels:
    app: config-server
spec:
  selector:
    app: config-server
  ports:
    - port: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-deployment
  namespace: odins-oddities
  labels:
    app: config-server
spec:
  selector:
    matchLabels:
      app: config-server
  replicas: 1
  template:
    metadata:
      namespace: odins-oddities
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: configserver:0.0.1-SNAPSHOT
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: config-server-config
            - secretRef:
                name: config-server-secret
